# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oliver Proudlock
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "http://oliverproudlock.com" # the base hostname & protocol for your site
twitter_username: oliverproudlock
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima

carousel: 
  - image: /images/carousel/op-carousel.jpg
  - image: /images/carousel/pstyle-carousel.jpg
  - image: /images/carousel/pstyle2-carousel.jpg
  - image: /images/carousel/samson-carousel.jpg

style_tiles:
  - image: /images/style/style1.jpg
  - image: /images/style/style2.jpg
  - image: /images/style/style3.jpg
  - image: /images/style/style4.jpg
  - image: /images/style/style5.jpg
  - image: /images/style/style6.jpg

# The home tile options
home_tiles:
  - title: Serge
    url: https://sergedenimes.com
    image: /images/home/serge.jpg
    new: true
  - title: Style
    url: http://proudlockstyle.com
    image: /images/home/style.jpg
    new: true
  - title: Fitness
    url: /fitness
    image: /images/home/fitness.jpg
    new: false
  - title: Travel
    url: /travel
    image: /images/home/travel.jpg
    new: false
