SectionPagesMenu = ""
baseURL = "http://oliverproudlock.com/"
languageCode = "en-gb"
theme = ""
title = "Oliver Proudlock"
paginate = 30

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 7
[[menu.main]]
name = "Shop"
url = "http://sergedenimes.com"
weight = 6
[[menu.main]]
identifier = "style"
name = "Style"
url = "/style/"
weight = 3
[[menu.main]]
identifier = "fitness"
name = "Fitness"
url = "/categories/fitness/"
weight = 4
[[menu.main]]
identifier = "travel"
name = "Travel"
url = "/categories/travel/"
weight = 5
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
contactemail = "ollie@oliverproudlock.com"
instatoken = "21686064.1677ed0.7157aa5ab77e47809b1b2d3753005e71"
instauser = "21686064"
[[params.socialIcons]]
icon = "instagram"
url = "https://www.instagram.com/proudlock/"
[[params.socialIcons]]
icon = "youtube"
url = "https://www.youtube.com/channel/UCeDi_2LhhvSIPI9DO7jNFNA"
[[params.socialIcons]]
icon = "twitter"
url = "https://twitter.com/oliverproudlock"
[[params.socialIcons]]
icon = "pinterest"
url = "https://pinterest.com/oliverproudlock"
[[params.socialIcons]]
icon = "depop"
url = "https://depop.com/proudlock"
