baseURL = "http://oliverproudlock.com/"
title = "Oliver Proudlock"

languageCode = "en-gb"
theme = ""

SectionPagesMenu = ""

[params]
    instaUser = "21686064"
    instaToken = "21686064.1677ed0.7157aa5ab77e47809b1b2d3753005e71"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 100

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 130

[[menu.main]]
    name = "Travel"
    identifier = "travel"
    url = "/categories/travel/"
    weight = 160

[[menu.main]]
    name = "Fitness"
    identifier = "fitness"
    url = "/categories/fitness/"
    weight = 170

[[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact/"
    weight = 180
